#!/usr/bin/env bash
#Write a Bash script that loops from 1 to 10 and:
x=0
while (( x < 10 ))
do
	if (( x == 3 ))
	then
		echo 'bad luck'
	elif (( x == 7 ))
	then
		echo 'good luck'
	else
		echo 'Best School'
	fi
	x=$(( x+1 ))
done
